#!/usr/bin/env cmake -P
# generate_keys.cmake
#
# Called by CMake at build time to scan the public_keys/ directory and
# produce generated_keys.hpp containing every .pem file as a string literal.
#
# Arguments (passed via -D):
#   KEYS_DIR    — path to the public_keys/ folder
#   OUTPUT_FILE — path to write generated_keys.hpp

if(NOT DEFINED KEYS_DIR OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "Usage: cmake -DKEYS_DIR=... -DOUTPUT_FILE=... -P generate_keys.cmake")
endif()

file(GLOB KEY_FILES "${KEYS_DIR}/*.pem")
list(SORT KEY_FILES)

set(entries "")
set(count 0)

foreach(key_path IN LISTS KEY_FILES)
    get_filename_component(key_name "${key_path}" NAME_WE)  # stem without extension
    file(READ "${key_path}" key_pem)

    # Escape backslashes and double-quotes, then turn newlines into \n in the literal
    string(REPLACE "\\" "\\\\" key_pem "${key_pem}")
    string(REPLACE "\"" "\\\"" key_pem "${key_pem}")
    string(REPLACE "\n" "\\n\"\n    \"" key_pem "${key_pem}")

    string(APPEND entries
        "    { \"${key_name}\", \"${key_pem}\" },\n")
    math(EXPR count "${count} + 1")
endforeach()

set(content
"// AUTO-GENERATED by generate_keys.cmake — do not edit by hand.
// Re-generated whenever files in public_keys/ change.

#pragma once
#include <cstddef>

struct EmbeddedKey {
    const char *name;  // filename stem, e.g. \"batch_001\"
    const char *pem;   // full PEM public key text
};

static const EmbeddedKey EMBEDDED_KEYS[] = {
${entries}};

static const size_t EMBEDDED_KEYS_COUNT = ${count};
")

file(WRITE "${OUTPUT_FILE}" "${content}")
message(STATUS "Generated ${OUTPUT_FILE} with ${count} public key(s)")